Wba.PE1.Webshop.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using pe1.Webshop.Domain;
using pe1.Webshop.Web.Data;
using pe1.Webshop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pe1.Webshop.Web.Controllers
{
    public class CategoryController : Controller
    {

        protected readonly WebshopContext _webshopDbContext;

        public CategoryController(WebshopContext webshopContext)
        {
            _webshopDbContext = webshopContext;
        }

        [Route("category/")]
        public IActionResult Index()
        {
            ViewBag.Title = "All categories";
            var viewModel = new CategoryIndexVM();
            var categories = _webshopDbContext.Categories
                .ToList();

            viewModel.Categories =
                categories.Select(category =>
            {
                return new CategoryDetailsVM(category);
            });

            return View(viewModel);
        }

        [Route("category/details/{id:int}")]
        public IActionResult Details(int id, string name)
        {
            var viewModel = new HomeIndexVM();
            var products = _webshopDbContext.Products
                .Include(p => p.Category)
                .Where(p => p.Category.Id == id)
                .ToList();

            viewModel.Products =
                products.Select(product =>
                {
                    return new HomeDetailsVM(product);
                });

            ViewBag.Title = name;

            return View(viewModel);
        }
    }
}

Wba.PE1.Webshop.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pe1.Webshop.Web.Controllers
{
    public class SearchController : Controller
    {
        [Route("search/")]
        public IActionResult Index()
        {

            return View();
        }


    }
}

Wba.PE1.Webshop.Web/Views/Shared/ProductDetailPartial.cshtml
@model HomeDetailsVM

<h2 class="page-title">Product details</h2>
<div class="flex-container">
    <div class="row item">
        <div class="col-md-3 col-sm-6 item">
            <div class="product-grid">
                <div class="product-image">
                    <a href="#" class="image">
                        <img class="pic-1" src="~/images/@Model.Image">
                    </a>
                    <ul class="product-links">
                        <li><a href="#"><i class="fa fa-search"></i> Add to cart</a></li>
                    </ul>
                </div>
                <div class="product-content">
                    <div class="title">
                        @Model.ProductName

                        <div class="category allign-left-text">
                            <p class="category">Category: @Model.Category</p>
                            <p class="category">Publisher: @Model.Publisher</p>
                            <p class="category">Serie: @Model.Serie</p>
                            <ul class="list-info">
                                @if (Model.Info != null)
                                {
                                    @foreach (var item in Model.Info)
                                    {
                                        <li class="category"> @item.Info.InfoText</li>
                                    }
                                }
                            </ul>
                        </div>
                    </div>
                    <div class="price">@Model.Price.ToString("c")</div>
                </div>
            </div>
        </div>
    </div>
</div>


<a class="button" style="vertical-align:middle" href="javascript: history.go(-1)"><span>Go back</span></a>

Wba.PE1.Webshop.Web/Views/Shared/ProductListPartial.cshtml
@*<div class="flex-container">
        @foreach (var product in Model)
        {
            <div class="item">
                <p>@product.ProductName</p>
                <img id="image" src="~/images/@product.Image" alt="Alternate Text" />
                <p>Category: @product.Category </p>
                <a asp-action="details" asp-controller="home" asp-route-id="@product.Id">View details</a>
            </div>
        }
    </div>*@
<head>
    <link href="~/css/Style.css" rel="stylesheet" />
</head>

<div class="flex-container">
    @foreach (var product in Model)
    {
        <div class="row item">
            <div class="col-md-3 col-sm-6 item">
                <div class="product-grid">
                    <div class="product-image">
                        <a href="#" class="image">
                            <img class="pic-1" src="~/images/@product.Image">
                        </a>
                        <ul class="product-links">
                            <li><a asp-action="details" asp-controller="home" asp-route-id="@product.Id"><i class="fa fa-shopping-bag"></i> View Details</a></li>
                            <li><a href="#"><i class="fa fa-search"></i> Add to cart</a></li>
                            <li><a asp-controller="products" asp-action="edit" asp-route-id="@product.Id"><i class="fa fa-shopping-bag"></i>Edit</a></li>
                            <li><a asp-controller="products" asp-action="delete" asp-route-id="@product.Id"><i class="fa fa-shopping-bag"></i>Delete</a></li>

                        </ul>
                    </div>
                    <div class="product-content">
                        <div class="title">
                        @product.ProductName
                            <p class="category">@product.Category</p>
                        </div>
                        <div class="price">@product.Price.ToString("c")</div>
                    </div>
                </div>
            </div>
        </div>
    }

</div>

Wba.PE1.Webshop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/Style.css">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
        asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </environment>
    <title></title>
</head>
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Ellen's GeekShop</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                    <li><a asp-area="" asp-controller="Search" asp-action="Index">Search</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<body>
    <div class="container body-content ">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Wba.PE1.Webshop.Web - Ellen Meulenijzer</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>