Wba.PE1.Webshop.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pe1.Webshop.Web.Controllers
{
    public class SearchController : Controller
    {
        [Route("search/")]
        public IActionResult Index()
        {

            return View();
        }


    }
}

Wba.PE1.Webshop.Web/Controllers/SearchResultController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using pe1.Webshop.Domain;
using pe1.Webshop.Domain.Entities;
using pe1.Webshop.Web.Data;
using pe1.Webshop.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pe1.Webshop.Web.Controllers
{
    public class SearchResultController : Controller
    {

        protected readonly WebshopContext _webshopDbContext;

        public SearchResultController(WebshopContext webshopContext)
        {
            _webshopDbContext = webshopContext;
        }

        [Route("SearchResult/AllMarvelComics")]
        public IActionResult AllMarvelComics()
        {
            ViewBag.Title = "All Marvel Comics: ";

            var homeIndexVM = new HomeIndexVM();
            var products = _webshopDbContext.Products
                .Include(p => p.Category)
                .Where(p => p.Serie.Id == 5)
                .ToList();

            homeIndexVM.Products =
                products.Select(product =>
                {
                    return new HomeDetailsVM(product);
                });

            return View(homeIndexVM);
        }

        [Route("SearchResult/AllAnimeFromAOT")]
        public IActionResult AllAnimeFromAOT()
        {
            ViewBag.Title = "Anime from serie Attack on Titan: ";


            var homeIndexVM = new HomeIndexVM();
            var products = _webshopDbContext.Products
                .Include(p => p.Category)
                .Where(p => p.Category.Id == 2 && p.Serie.Id == 1)
                .ToList();

            homeIndexVM.Products =
                products.Select(product =>
                {
                    return new HomeDetailsVM(product);
                });
            return View(homeIndexVM);
        }

        [Route("SearchResult/AllTakaraWithPriceHigherThan40")]
        public IActionResult AllTakaraWithPriceHigherThan40()
        {
            ViewBag.Title = "Takara with price higher than 40: ";

            var homeIndexVM = new HomeIndexVM();
            var products = _webshopDbContext.Products
                .Include(p => p.Category)
                .Where(p => p.Publisher.Id == 2 && p.Price > 40)
                .ToList();

            homeIndexVM.Products =
                products.Select(product =>
                {
                    return new HomeDetailsVM(product);
                });
            return View(homeIndexVM);


        }

        [Route("SearchResult/AllMHAWithPriceLowerThan10")]
        public IActionResult AllMHAWithPriceLowerThan10()
        {
            ViewBag.Title = "My Hero Academia with price lower than 10: ";

            var homeIndexVM = new HomeIndexVM();
            var products = _webshopDbContext.Products
                .Include(p => p.Category)
                .Where(p => p.Serie.Id == 2 && p.Price < 10)
                .ToList();

            homeIndexVM.Products =
                products.Select(product =>
                {
                    return new HomeDetailsVM(product);
                });
            return View(homeIndexVM);

        }
    }
}

Wba.PE1.Webshop.Web/Views/Search/Index.cshtml
<div>
    <h2 class="page-title">@ViewBag.Title</h2>

    <div class="buttons">
        <a class="item" asp-action="AllMarvelComics" asp-controller="SearchResult">
            <p><span class="bg"></span><span class="base"></span><span class="text">All Marvel comics</span></p>
        </a>
        <a class="item" asp-action="AllAnimeFromAOT" asp-controller="SearchResult">
            <p><span class="bg"></span><span class="base"></span><span class="text">All anime from Attack on Titan</span></p>
        </a>        <a class="item" asp-action="AllTakaraWithPriceHigherThan40" asp-controller="SearchResult">
            <p><span class="bg"></span><span class="base"></span><span class="text">All Takara with price higher than 40</span></p>
        </a>        <a class="item" asp-action="AllMHAWithPriceLowerThan10" asp-controller="SearchResult">
            <p><span class="bg"></span><span class="base"></span><span class="text">All My Hero Academia with price lower than 10</span></p>
        </a>

    </div>
</div>